openapi: "3.0.0"
info:
  title: "SAIB Consents Management"
  description: "## SAIB Consents management"
  version: "1.0.0"
servers:
  - url: "/open-banking/consent-management"
tags:
  - name: Consent Management
    description: Consents Management Resource
paths:
  /customer-consents/{ConsentId}:
    get:
      tags:
        - "Customer Consents"
      summary: "Get Customer Consent"
      description: |
        Retrieve Customer Consents               
      operationId: "GetCustomerConsentsConsentId"
      parameters:
        - $ref: "#/components/parameters/ConsentId"
        - $ref: "#/components/parameters/x-fapi-customer-ip-address"
        - $ref: "#/components/parameters/x-fapi-interaction-id"
        - $ref: "#/components/parameters/x-customer-user-agent"
      responses:
        '200':
          $ref: "#/components/responses/200AccountAccessConsentsConsentIdRead"
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '403':
          $ref: "#/components/responses/403Error"
        '405':
          $ref: "#/components/responses/405Error"
        '406':
          $ref: "#/components/responses/406Error"
        '429':
          $ref: "#/components/responses/429Error"
        '500':
          $ref: "#/components/responses/500Error"
    delete:
      tags:
        - "Customer Consents"
      summary: "Delete Customer Consent"
      description: |
        Retrieve Customer Consents               
      operationId: "DeleteCustomerConsentsConsentId"
      parameters:
        - $ref: "#/components/parameters/ConsentId"
        - $ref: "#/components/parameters/x-fapi-customer-ip-address"
        - $ref: "#/components/parameters/x-fapi-interaction-id"
        - $ref: "#/components/parameters/x-customer-user-agent"
      responses:
        '204':
            description: Delete Account Access Consents by Consent Id
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '403':
          $ref: "#/components/responses/403Error"
        '405':
          $ref: "#/components/responses/405Error"
        '406':
          $ref: "#/components/responses/406Error"
        '429':
          $ref: "#/components/responses/429Error"
        '500':
          $ref: "#/components/responses/500Error"
  /customer-consents:
      get:
        tags:
          - "Customer Consents"
        summary: "Get Customer Consents"
        description: |
          Retrieve Customer Consents               
        operationId: "GetCustomerConsents"
        parameters:
          - $ref: "#/components/parameters/x-fapi-customer-ip-address"
          - $ref: "#/components/parameters/x-fapi-interaction-id"
          - $ref: "#/components/parameters/x-customer-user-agent"
        responses:
          '200':
            $ref: "#/components/responses/200CustomerConsents"
          '400':
            $ref: "#/components/responses/400Error"
          '401':
            $ref: "#/components/responses/401Error"
          '403':
            $ref: "#/components/responses/403Error"
          '405':
            $ref: "#/components/responses/405Error"
          '406':
            $ref: "#/components/responses/406Error"
          '429':
            $ref: "#/components/responses/429Error"
          '500':
            $ref: "#/components/responses/500Error"
components:
  ############################################
  # RESPONSES
  ############################################
  responses:
    403Error:
      description: "Forbidden"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
      content:
        application/json; charset=utf-8:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
        application/json:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
    404Error:
      description: "Not found"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    405Error:
      description: "Method Not Allowed"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    406Error:
      description: "Not Acceptable"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    415Error:
      description: "Unsupported Media Type"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    429Error:
      description: "Too Many Requests"
      headers:
        Retry-After:
          description: "Number in seconds to wait"
          schema:
            type: "integer"
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          schema:
            type: "string"
    500Error:
      description: "Internal Server Error"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
      content:
        application/json; charset=utf-8:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
        application/json:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
    401Error:
      description: "Unauthorized"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    400Error:
      description: "Bad request"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
      content:
        application/json; charset=utf-8:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
        application/json:
          schema:
            $ref: "#/components/schemas/OBErrorResponse"
    204AccountAccessConsentsConsentIdDeleted:
      description: "No Content"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
    200AccountAccessConsentsConsentIdRead:
      description: "Account Access Consents Read"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
      content:
        application/json; charset=utf-8:
          schema:
            $ref: "#/components/schemas/OBReadConsentResponse"
        application/json:
          schema:
            $ref: "#/components/schemas/OBReadConsentResponse"
    200CustomerConsents:
      description: "Account Access Consents Read"
      headers:
        x-fapi-interaction-id:
          description: "An RFC4122 UID used as a correlation id."
          required: true
          schema:
            type: "string"
      content:
        application/json; charset=utf-8:
          schema:
            $ref: "#/components/schemas/OBReadConsentListResponse"
        application/json:
          schema:
            $ref: "#/components/schemas/OBReadConsentListResponse"

  ############################################
  # SCHEMAS
  ############################################
  schemas:
    Purpose:
      description: "Purpose" 
      type: "string"
      enum: [Account Aggregation, Personal Finance Manager, Electronic Verification,E-Statement, Credit Assessment, Tax Filing, Enterprise Financial Management, Letter Of Guarantee, Other]
    OnBehalfOf:
      type: "object"
      description: "On Behalf Of"
      properties:
        TradingName:
          type: "string"
          example: "Acme Accounting Trading Name"
        LegalName:
          type: "string"
          example: "Acme Accounting Legal Name"
        IdentifierType:
          type: "string"
          enum: ["Other"]
        Identifier:
          type: "string"
          example: "abcd1234"
    OBErrorResponse:
      title: "OBErrorResponse"
      description: "An array of detail error codes, and messages, and URLs to documentation to help remediation."
      type: "object"
      properties:
        Errors:
          items:
            $ref: "#/components/schemas/OBError"
          type: "array"
          minItems: 1
      required:
        - "Errors"
      additionalProperties: false
    OBError:
      title: "OBError"
      type: "object"
      properties:
        Code:
          description: "Low level textual error code, e.g., KSAOB.Field.Missing"
          type: "string"
          enum:
            - "KSAOB.AccessToken.Unauthorized"
            - "KSAOB.AccessToken.InvalidScope"
            - "KSAOB.Consent.Revoked"
            - "KSAOB.Consent.TransientAccountAccessFailure"
            - "KSAOB.Consent.AccountTemporarilyBlocked"
            - "KSAOB.Consent.PermanentAccountAccessFailure"
            - "KSAOB.Consent.Invalid"
            - "KSAOB.JWS.InvalidSignature"
            - "KSAOB.JWS.Malformed"
            - "KSAOB.JWS.InvalidClaim"
            - "KSAOB.JWS.InvalidHeader"
            - "KSAOB.GenericRecoverableError"
            - "KSAOB.GenericError"
            - "KSAOB.JWE.DecryptionError"
            - "KSAOB.JWE.InvalidHeader"
            - "KSAOB.Event.UnexpectedEvent"
            - "KSAOB.Body.InvalidFormat"
            - "KSAOB.Resource.InvalidResourceId"
            - "KSAOB.Resource.InvalidFormat"
            - "KSAOB.Consent.BusinessRuleViolation"
        Message:
          description: "A description of the error that occurred. e.g., 'A mandatory field isn't supplied' or 'RequestedExecutionDateTime must be in future'\nOBIE doesn't standardise this field"
          type: "string"
          minLength: 1
          maxLength: 500
        Path:
          description: "Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency"
          type: "string"
          minLength: 1
          maxLength: 500
        Url:
          description: "URL to help remediate the problem, or provide more information, or to API Reference, or help etc"
          type: "string"
      required:
        - "Code"
        - "Message"
      additionalProperties: false
      minProperties: 1                
    OBAccountIdList:
      title: "OBAccountArrayId" 
      type: "array"
      items:
         $ref: "#/components/schemas/OBAccount"  
    OBAccount:
      title: "OBAccount"
      type: "object"
      properties:
        AccountNumber:
          type: "string"
        AccountType:
          type: "string"
    CreationDateTime:
      title: "CreationDateTime"
      description: "Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00"
      type: "string"
      format: "date-time"    
    OBConsentPermissions:
      type: "array"
      description: "Specifies the Open Banking account access data types. This is a list of the data groups being consented by the PSU, and requested for authorization with the PASP."
      items:
        type: "string"
        enum:
          - "ReadAccountsBasic"             # Ability to read basic account information
          - "ReadAccountsDetail"            # Ability to read account identification details
          - "ReadBalances"                  # Ability to read all balance information
          - "ReadParty"                     # Required to access GET /accounts/{AccountId}/parties. Ability to read party information on the account owner. 
          - "ReadPartyPSU"                  # Required to access GET /parties. Ability to read party information on the account owner.
          - "ReadPartyPSUIdentity"          # Required to access GET /parties. Include the above and additional information to fulfil KYC information e.g. The account name, address, date of birth, national ID and residency number 
          - "ReadBeneficiariesBasic"        # Ability to read basic beneficiary details
          - "ReadBeneficiariesDetail"       # Ability to read account identification details for the beneficiary
          - "ReadTransactionsBasic"         # Ability to read basic transaction information
          - "ReadTransactionsDetail"        # Ability to read transaction data elements which may hold silent party details
          - "ReadTransactionsCredits"       # Ability to read only credit transactions
          - "ReadTransactionsDebits"        # Ability to read only debit transactions
          - "ReadScheduledPaymentsBasic"    # Ability to read basic scheduled payment details
          - "ReadScheduledPaymentsDetail"   # Ability to read additional scheduled payment details
          - "ReadDirectDebits"              # Ability to read all direct debit information
          - "ReadStandingOrdersBasic"       # Ability to read basic standing order Information
          - "ReadStandingOrdersDetail"      # Ability to read additional Standing order Information
      minItems: 1
    StatusUpdateDateTime:
      title: "StatusUpdateDateTime" 
      description: "Date and time at which the account resource status was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00"
      type: "string"
      format: "date-time"
    OBReadConsentListResponse:
      title: "OBReadConsentListResponse"
      type: "array"
      items: 
          $ref: "#/components/schemas/OBReadConsentResponse"     
      additionalProperties: false
    OBReadConsentResponse:
      title: "OBReadConsentResponse"
      type: "object"
      required:
        - "Data"
        - "Links"
        - "Meta"
      properties:
        Data:
          type: "object"
          required:
            - "ConsentId"
            - "CreationDateTime"
            - "Status"
            - "StatusUpdateDateTime"
            - "Permissions"
          properties:
            ConsentId:
              description: "Unique identification as assigned to identify the account access consent resource."
              type: "string"
              minLength: 1
              maxLength: 128
            CreationDateTime:
              $ref: "#/components/schemas/CreationDateTime"
            Status:
              $ref: "#/components/schemas/ConsentStatus"
            StatusUpdateDateTime:
              $ref: "#/components/schemas/StatusUpdateDateTime"
            ExpirationDateTime:
              description: "Specified date and time the permissions will expire.\nIf this is not populated, the permissions will be open ended.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00"
              type: "string"
              format: "date-time"
            TransactionFromDateTime:
              description: "Specified start date and time for the transaction query period.\nIf this is not populated, the start date will be open ended, and data will be returned from the earliest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00"
              type: "string"
              format: "date-time"
            TransactionToDateTime:
              description: "Specified end date and time for the transaction query period.\nIf this is not populated, the end date will be open ended, and data will be returned to the latest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00"
              type: "string"
              format: "date-time"
            AccountList:
               $ref: "#/components/schemas/OBAccountIdList"
            Permissions:
              $ref: "#/components/schemas/OBConsentPermissions"
            OnBehalfOf:
               $ref: "#/components/schemas/OnBehalfOf"
            Purpose:
              type: "array"
              items:
                $ref: "#/components/schemas/Purpose"
      additionalProperties: false          
    ConsentStatus:
      description: "Specifies the status of consent resource in code form."
      type: "string"
      enum:
        - "Authorized"
        - "AwaitingAuthorization"
        - "Rejected"
        - "Revoked"
        - "Expired"
  ############################################
  # PARAMETERS
  ############################################
  parameters:
    #################################################
    # HEADER PARAMETERS
    #################################################
    x-customer-user-agent:
      in: "header"
      name: "x-customer-user-agent"
      description: "Indicates the user-agent that the PSU is using."
      required: false
      schema:
        type: "string"
    x-fapi-customer-ip-address:
      in: "header"
      name: "x-fapi-customer-ip-address"
      required: false
      description: "The PSU's IP address if the PSU is currently logged in with the TPP."
      schema:
        type: "string"
    x-fapi-interaction-id:
      in: "header"
      name: "x-fapi-interaction-id"
      required: false
      description: "An RFC4122 UID used as a correlation id."
      schema:
        type: "string"
    #################################################
    # PATH PARAMETERS
    #################################################
    ConsentId:
      name: "ConsentId"
      in: "path"
      description: "ConsentId"
      required: true
      schema:
        type: "string"
    AccountId:
      name: "AccountId"
      in: "path"
      description: "AccountId"
      required: true
      schema:
        type: "string"
